# DCWP Consumer Complaints Analysis

## 1. Project Overview

This project analyzes consumer complaint records published by the New York City Department of Consumer and Worker Protection (DCWP).

The dataset contains information about consumer complaints, businesses, complaint categories, intake channels, complaint results, referrals, locations, and other related details.

The purpose of this project is to clean and prepare the dataset for further exploratory data analysis (EDA). Data cleaning is an important step because real-world datasets may contain missing values, inconsistent entries, duplicate records, incorrect data types, and other data-quality issues.

### Objectives of Data Cleaning

The main objectives of the data-cleaning process are:

- Understand the structure and contents of the dataset.
- Identify missing values and highly incomplete columns.
- Clean and convert financial values into suitable numeric formats.
- Convert date columns into proper datetime format.
- Identify and handle inconsistent or placeholder values.
- Standardize categorical data where appropriate.
- Correct data types for identifier and code-related columns.
- Check for duplicate records.
- Validate the final cleaned dataset.
- Save the cleaned dataset for further analysis.

The cleaned dataset will be used for the Exploratory Data Analysis (EDA) phase of the project.

## 2. Importing Required Libraries

The following Python libraries are used in this project:

- **Pandas** – for data loading, manipulation, cleaning, and analysis.
- **NumPy** – for handling missing values and numerical operations.
- **Matplotlib** – for creating visualizations.
- **Seaborn** – for statistical visualizations.

These libraries provide the basic tools required for the data-cleaning and analysis process.

In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)

## 3. Loading the Dataset

The raw consumer complaints dataset is stored as a CSV file in the project's `data/raw` folder.

The dataset is loaded into a Pandas DataFrame so that it can be inspected, cleaned, and prepared for further analysis.

The raw dataset is kept unchanged so that the original data remains available for reference and reproducibility.

In [6]:
file_path = "C:\\Users\\User\\Desktop\\DA FINAL PROJECT -DCWP-Consumer-Complaints-Analysis\\data\\raw\\DCWP_Consumer_Complaints_20260918.csv"

df = pd.read_csv(file_path)
print("Dataset loaded successfully.")

Dataset loaded successfully.

## 4. Initial Dataset Inspection

Before performing any cleaning operations, the dataset is inspected to understand its structure, size, columns, data types, and sample records.

This initial inspection helps identify potential data-quality issues that need to be addressed during the cleaning process.

In [7]:
df.head()

,Record ID,Intake Date,Intake Channel,311 SR Number,Business Category,Complaint Code,Business Unique ID,Business Name,Result Date,Result,Referred To,Contract Cancelled Amount,Refund Amount,Address Type,Building Nbr,Street1,Street2,Street3,Unit Type,Apt/Suite,City,State,Postcode,Borough,Community Board,Council District,BIN,BBL,NTA,Census Block (2010),Census Tract (2010),Latitude,Longitude
0,000001-2026-CMPL,01/01/2026,311,311-25776008,Garage & Parking Lot,Non-Delivery of Goods - N01,BA-1758638-2026,PLATINUM PLUS GARAGE,02/01/2026,Requested Information Not Provided,NaN,NaN,NaN,Complete Address,350,E 30TH ST,NaN,NaN,NaN,NaN,NEW YORK,NY,10016,Manhattan,106.0,4.0,1020634.0,1.009358e+09,MN20,3000.0,70.0,40.741635,-73.976219
1,000002-2026-CMPL,01/01/2026,311,311-25776542,Tow Truck Company,Lost/Stolen/Damaged Property,BA-1758639-2026,Legacy Towing,02/01/2026,Requested Information Not Provided,NaN,NaN,NaN,Complete Address,13101,39TH AVE,NaN,NaN,NaN,NaN,FLUSHING,NY,11354,Queens,407.0,20.0,4112199.0,4.049630e+09,QN22,2008.0,871.0,40.758836,-73.835231
2,000003-2026-CMPL,01/01/2026,311,311-25776844,Specialized Vending License - MFV,Advertising/Misleading - A02,BA-1758640-2026,The flavor of the new yorm,01/02/2026,Insufficient Info Received,NaN,NaN,NaN,Complete Address,134,W 43RD ST,NaN,NaN,NaN,NaN,NEW YORK,NY,10036,Manhattan,105.0,4.0,1087268.0,1.009950e+09,MN17,1005.0,119.0,40.755920,-73.984606
3,000004-2026-CMPL,01/01/2026,Online,NaN,Garage & Parking Lot,Other - Z01,BA-1287019-2022,"LAUREATE GARAGE, LLC",02/15/2026,Requested Information Not Provided,NaN,NaN,NaN,Complete Address,2148,BROADWAY,NaN,NaN,NaN,NaN,NEW YORK,NY,10023,Manhattan,107.0,6.0,1088786.0,1.011678e+09,MN12,5002.0,163.0,40.781385,-73.981177
4,000005-2026-CMPL,01/01/2026,Online,NaN,Garage & Parking Lot,Non-Delivery of Service - N02,BA-1758642-2026,LAUREATE GARAGE LLC,02/15/2026,Requested Information Not Provided,NaN,NaN,NaN,Complete Address,NaN,2148 Broadway,NaN,NaN,NaN,NaN,New York,NY,10023,Manhattan,107.0,6.0,1088786.0,1.011678e+09,MN12,5002.0,163.0,40.781385,-73.981177

In [21]:
df.shape

(76527, 33)

In [22]:
df.columns.tolist()

['Record ID',
 'Intake Date',
 'Intake Channel',
 '311 SR Number',
 'Business Category',
 'Complaint Code',
 'Business Unique ID',
 'Business Name',
 'Result Date',
 'Result',
 'Referred To',
 'Contract Cancelled Amount',
 'Refund Amount',
 'Address Type',
 'Building Nbr',
 'Street1',
 'Street2',
 'Street3',
 'Unit Type',
 'Apt/Suite',
 'City',
 'State',
 'Postcode',
 'Borough',
 'Community Board',
 'Council District',
 'BIN',
 'BBL',
 'NTA',
 'Census Block (2010)',
 'Census Tract (2010)',
 'Latitude',
 'Longitude']

In [23]:
df.dtypes

Record ID                     object
Intake Date                   object
Intake Channel                object
311 SR Number                 object
Business Category             object
Complaint Code                object
Business Unique ID            object
Business Name                 object
Result Date                   object
Result                        object
Referred To                   object
Contract Cancelled Amount     object
Refund Amount                 object
Address Type                  object
Building Nbr                  object
Street1                       object
Street2                       object
Street3                       object
Unit Type                     object
Apt/Suite                     object
City                          object
State                         object
Postcode                      object
Borough                       object
Community Board              float64
Council District             float64
BIN                          float64
BBL                          float64
NTA                           object
Census Block (2010)          float64
Census Tract (2010)          float64
Latitude                     float64
Longitude                    float64
dtype: object

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 76527 entries, 0 to 76526
Data columns (total 33 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Record ID                  76527 non-null  object
 1   Intake Date                76527 non-null  object
 2   Intake Channel             76527 non-null  object
 3   311 SR Number              53763 non-null  object
 4   Business Category          75129 non-null  object
 5   Complaint Code             65750 non-null  object
 6   Business Unique ID         74030 non-null  object
 7   Business Name              73154 non-null  object
 8   Result Date                76527 non-null  object
 9   Result                     76527 non-null  object
 10  Referred To                28002 non-null  object
 11  Contract Cancelled Amount  46 non-null     object
 12  Refund Amount              1509 non-null   object
 13  Address Type               72887 non-null  object
 14  Building Nbr               64041 non-null  object
 15  Street1                    72837 non-null  object
 16  Street2                    3167 non-null   object
 17  Street3                    141 non-null    object
 18  Unit Type                  3996 non-null   object
 19  Apt/Suite                  6733 non-null   object
 20  City                       70599 non-null  object
 21  State                      72806 non-null  object
 22  Postcode                   72780 non-null  object
 23  Borough                    66914 non-null  object
 24  Community Board            65935 non-null  float64
 25  Council District           65935 non-null  float64
 26  BIN                        61148 non-null  float64
 27  BBL                        61148 non-null  float64
 28  NTA                        63073 non-null  object
 29  Census Block (2010)        63073 non-null  float64
 30  Census Tract (2010)        65932 non-null  float64
 31  Latitude                   66400 non-null  float64
 32  Longitude                  66400 non-null  float64
dtypes: float64(8), object(25)
memory usage: 19.3+ MB

## 5. Missing Value Analysis

Missing values are common in real-world datasets. Before deciding how to handle them, the number and percentage of missing values in each column are examined.

This helps identify columns that are highly incomplete and determine whether the missing values should be removed, retained, or handled in another way.

In [25]:
missing_count = df.isnull().sum()

missing_percentage = (df.isnull().sum() / len(df)) * 100

missing_summary = pd.DataFrame({
    "Missing Values": missing_count,
    "Missing Percentage": missing_percentage
})

missing_summary = missing_summary.sort_values(
    by="Missing Percentage",
    ascending=False
)

missing_summary

                           Missing Values  Missing Percentage
Contract Cancelled Amount           76481           99.939890
Street3                             76386           99.815751
Refund Amount                       75018           98.028147
Street2                             73360           95.861591
Unit Type                           72531           94.778314
Apt/Suite                           69794           91.201798
Referred To                         48525           63.408993
311 SR Number                       22764           29.746364
BBL                                 15379           20.096175
BIN                                 15379           20.096175
Census Block (2010)                 13454           17.580723
NTA                                 13454           17.580723
Building Nbr                        12486           16.315810
Complaint Code                      10777           14.082611
Census Tract (2010)                 10595           13.844787
Council District                    10592           13.840867
Community Board                     10592           13.840867
Latitude                            10127           13.233238
Longitude                           10127           13.233238
Borough                              9613           12.561580
City                                 5928            7.746286
Postcode                             3747            4.896311
State                                3721            4.862336
Street1                              3690            4.821828
Address Type                         3640            4.756491
Business Name                        3373            4.407595
Business Unique ID                   2497            3.262901
Business Category                    1398            1.826806
Intake Date                             0            0.000000
Result                                  0            0.000000
Result Date                             0            0.000000
Intake Channel                          0            0.000000
Record ID                               0            0.000000

### Removing Highly Sparse Columns

The following address-detail columns contained more than 90% missing values and were removed because they provided limited information for the analysis:

- Street2
- Street3
- Unit Type
- Apt/Suite

Financial columns with high missing values were retained because their available values may provide useful information.

In [29]:
df.drop(
    columns=["Street2", "Street3", "Unit Type", "Apt/Suite"],
    inplace=True
)

print(df.shape)

(76527, 29)

In [32]:
duplicate_count = df.duplicated().sum()

print("Number of duplicate rows:", duplicate_count)

Number of duplicate rows: 0

## 6. Cleaning Financial Columns

The `Contract Cancelled Amount` and `Refund Amount` columns contain monetary values.

The values contain currency symbols and commas, which need to be removed before converting the columns into numeric format.

Missing values are retained because a missing amount does not necessarily mean that the amount was zero.

In [11]:
df[["Contract Cancelled Amount", "Refund Amount"]].describe()

       Contract Cancelled Amount Refund Amount
count                         46          1509
unique                        44           607
top                       $3,000       $10,000
freq                           2            82

In [10]:
df[["Contract Cancelled Amount", "Refund Amount"]].head(20)

   Contract Cancelled Amount Refund Amount
0                        NaN           NaN
1                        NaN           NaN
2                        NaN           NaN
3                        NaN           NaN
4                        NaN           NaN
5                        NaN           NaN
6                        NaN           NaN
7                        NaN           NaN
8                        NaN           NaN
9                        NaN           NaN
10                       NaN           NaN
11                       NaN           NaN
12                       NaN           NaN
13                       NaN           NaN
14                       NaN           NaN
15                       NaN           NaN
16                       NaN           NaN
17                       NaN           NaN
18                       NaN           NaN
19                       NaN          $110

In [36]:
df["Contract Cancelled Amount"] = (
    df["Contract Cancelled Amount"]
    .astype("string")
    .str.replace("$", "", regex=False)
    .str.replace(",", "", regex=False)
)

df["Refund Amount"] = (
    df["Refund Amount"]
    .astype("string")
    .str.replace("$", "", regex=False)
    .str.replace(",", "", regex=False)
)

df["Contract Cancelled Amount"] = pd.to_numeric(
    df["Contract Cancelled Amount"],
    errors="coerce"
)

df["Refund Amount"] = pd.to_numeric(
    df["Refund Amount"],
    errors="coerce"
)

In [39]:
df[["Contract Cancelled Amount", "Refund Amount"]].dtypes

Contract Cancelled Amount    Int64
Refund Amount                Int64
dtype: object

In [40]:
df[["Contract Cancelled Amount", "Refund Amount"]].head(20)

    Contract Cancelled Amount  Refund Amount
0                        <NA>           <NA>
1                        <NA>           <NA>
2                        <NA>           <NA>
3                        <NA>           <NA>
4                        <NA>           <NA>
5                        <NA>           <NA>
6                        <NA>           <NA>
7                        <NA>           <NA>
8                        <NA>           <NA>
9                        <NA>           <NA>
10                       <NA>           <NA>
11                       <NA>           <NA>
12                       <NA>           <NA>
13                       <NA>           <NA>
14                       <NA>           <NA>
15                       <NA>           <NA>
16                       <NA>           <NA>
17                       <NA>           <NA>
18                       <NA>           <NA>
19                       <NA>            110

In [41]:
df[["Intake Date", "Result Date"]].dtypes

Intake Date    object
Result Date    object
dtype: object

In [42]:
df[["Intake Date", "Result Date"]].head(10)

  Intake Date Result Date
0  01/01/2026  02/01/2026
1  01/01/2026  02/01/2026
2  01/01/2026  01/02/2026
3  01/01/2026  02/15/2026
4  01/01/2026  02/15/2026
5  01/01/2026  01/02/2026
6  01/01/2026  01/05/2026
7  01/01/2026  02/01/2026
8  01/01/2026  02/01/2026
9  01/01/2026  01/16/2026

## 7. Cleaning Date Columns

The `Intake Date` and `Result Date` columns contain dates in text format.

These columns are converted to the datetime format so that they can be used correctly for date-based analysis.

In [13]:
df["Intake Date"] = pd.to_datetime(
    df["Intake Date"],
    format="%m/%d/%Y",
    errors="coerce"
)

df["Result Date"] = pd.to_datetime(
    df["Result Date"],
    format="%m/%d/%Y",
    errors="coerce"
)

In [14]:
df[["Intake Date", "Result Date"]].dtypes

Intake Date    datetime64[ns]
Result Date    datetime64[ns]
dtype: object

### Checking Date Consistency

The `Result Date` should normally occur on or after the `Intake Date`.

Records where the `Result Date` occurs before the `Intake Date` are checked for possible date inconsistencies.

In [16]:
invalid_dates = df[df["Result Date"] < df["Intake Date"]]

invalid_dates[["Record ID", "Intake Date", "Result Date", "Result"]]

              Record ID Intake Date Result Date                Result
28866  042731-2024-CMPL  2024-07-27  2024-07-26              Referred
63892   10355-2023-CMPL  2023-07-27  2023-07-20  Advised to Sue - ATS

In [17]:
df.loc[df["Result Date"] < df["Intake Date"], "Result Date"] = pd.NaT

In [18]:
print("Remaining inconsistent dates:",
      (df["Result Date"] < df["Intake Date"]).sum())

Remaining inconsistent dates: 0

The two records with inconsistent date order were identified. Since the correct dates could not be determined from the available data, the inconsistent `Result Date` values were set to missing rather than assigning assumed dates.

In [46]:
df["City"].value_counts(dropna=False)

City
BROOKLYN            18322
NEW YORK            17890
BRONX                9504
NaN                  5928
STATEN ISLAND        1967
                    ...
DURYEA                  1
COLORADO SPRINGS        1
Elche                   1
Louisville              1
Fordham Heights         1
Name: count, Length: 1382, dtype: int64

In [47]:
df["Intake Channel"].value_counts(dropna=False)

Intake Channel
311                 53771
Online              17524
Email/Fax            2634
Hardcopy             2073
Cloned                264
Phone                 245
Walk-In                11
External Affairs        5
Name: count, dtype: int64

In [48]:
df["State"].value_counts(dropna=False)

State
NY             70657
NaN             3721
NJ               384
CA               297
Outside USA      135
FL               133
TX               115
PA               112
WA                70
CO                69
MN                68
MA                67
IL                66
OH                57
VA                56
GA                53
SC                51
CT                46
DE                40
MI                39
UT                39
NC                37
NV                26
MO                23
TN                21
MD                16
IN                14
SD                13
AZ                13
WI                12
AR                11
OR                10
DC                 9
AL                 8
LA                 7
KS                 6
KY                 6
IA                 5
NH                 3
OK                 3
NE                 2
WV                 1
ID                 1
ME                 1
MS                 1
WY                 1
ND                 1
NM                 1
Name: count, dtype: int64

In [49]:
df["Borough"].value_counts(dropna=False)

Borough
Manhattan        19712
Brooklyn         19305
Queens           15394
Bronx             9954
NaN               9613
Staten Island     1983
Outside NYC        566
Name: count, dtype: int64

In [50]:
df["Result"].value_counts(dropna=False)

Result
Referred                                              25633
Requested Information Not Provided                    23658
Complaint Review Complete                             11060
Insufficient Info Received                             4885
No Jurisdiction                                        1919
Information Provided                                   1412
Advised to Sue - ATS                                   1302
Duplicate Complaint - DUP                              1051
Resolved and Consumer Satisfied - SPF                  1007
No Business Response - NVR                              996
Cash Amount - AMT                                       808
No Consumer Response - NCR                              696
Credit Card Refund and/or Contract Cancelled - CRC      399
No Satisfactory Agreement - NSA                         335
Business Reported                                       243
Referred to Outside - RTO                               217
Inspection Requested                                    180
Consumer Took Action - CTA                              119
Bill Reduced - BLR                                      117
Store Credit - SCR                                      104
Wrong Business and Null and Void - NUL                   73
Goods Repaired - GRS                                     73
Unable to Locate Business- ULV                           51
Goods Received - GDR                                     44
Goods Exchanged - GEX                                    34
Consumer Withdrew Complaint - CWC                        33
Complaint Invalid - CIN                                  33
Referred to Hearing - RTH                                27
Technical Problem                                         5
Referred to Manufacturer - RMF                            4
Agency Collected Judgement - ACJ                          4
Provider Feedback Received                                2
Unable to Locate Customer - ULC                           2
Out of Business - OOB                                     1
Name: count, dtype: int64

In [51]:
df["Address Type"].value_counts(dropna=False)

Address Type
Complete Address               69639
NaN                             3640
Cross Street (Intersection)     2859
Place (Landmark)                 239
Block                            142
P.O. Box                           8
Name: count, dtype: int64

In [21]:
df["Business Category"].value_counts(dropna=False)

Business Category
Other                                                       11105
Misc Non-Food Retail                                         6077
Tow Truck Company                                            5587
Restaurant                                                   3835
Supermarket                                                  3460
                                                            ...
Collection Business Category                                    1
Gaming Cafe                                                     1
Amusement Device Portable                                       1
Motion Picture Operator - 123                                   1
Games of Chance - Raffle with Net Proceeds Under $30,000        1
Name: count, Length: 116, dtype: int64

In [19]:
df["Referred To"].value_counts(dropna=False)

Referred To
NaN                             48525
Other                            7484
NYC Department of Sanitation     3820
-                                2442
NYC Police Department            1833
                                ...
INS-000895326                       1
INS-000886316                       1
INS-000890975                       1
INS-000886716                       1
INS-000974629                       1
Name: count, Length: 386, dtype: int64

### Handling Placeholder Values

Some categorical fields contain placeholder values such as `-`, `Unknown`, `No name`, `none`, and `0`.

These values do not represent meaningful information, so they are treated as missing values where appropriate.

In [22]:
(df == "-").sum().sort_values(ascending=False)

Referred To                  2442
Business Name                   8
Record ID                       0
Council District                0
City                            0
State                           0
Postcode                        0
Borough                         0
Community Board                 0
BIN                             0
Unit Type                       0
BBL                             0
NTA                             0
Census Block (2010)             0
Census Tract (2010)             0
Latitude                        0
Apt/Suite                       0
Street2                         0
Street3                         0
Intake Date                     0
Street1                         0
Building Nbr                    0
Address Type                    0
Refund Amount                   0
Contract Cancelled Amount       0
Result                          0
Result Date                     0
Business Unique ID              0
Complaint Code                  0
Business Category               0
311 SR Number                   0
Intake Channel                  0
Longitude                       0
dtype: int64

In [55]:
df[df["Business Name"] == "-"][["Business Name", "Business Category", "Result", "Referred To"]]

,Business Name,Business Category,Result,Referred To
3833,-,Electronics Store,Insufficient Info Received,NaN
24571,-,Specialized Vending License - MFV,Referred,NYC Department of Sanitation
26401,-,Home Improvement Contractor,Requested Information Not Provided,NaN
27139,-,Garage & Parking Lot,Referred,NYC Police Department
27684,-,Construction Labor Provider,No Jurisdiction,NaN
28198,-,Pedicab Driver,Requested Information Not Provided,NaN
30523,-,Stoop Line Stand,Referred,NYC Department of Sanitation
33008,-,Other,Referred,NYS Department of Motor Vehicles

In [24]:
df["Referred To"] = df["Referred To"].replace("-", "Not Specified")

df["Business Name"] = df["Business Name"].replace("-", np.nan)
df["311 SR Number"] = df["311 SR Number"].replace("0", np.nan)

df["Building Nbr"] = df["Building Nbr"].replace("0", np.nan)
df["Postcode"] = df["Postcode"].replace("0", np.nan)

df["Street1"] = df["Street1"].replace("0", np.nan)

In [25]:
#Checking
(df == "-").sum().sort_values(ascending=False).head()

Record ID              0
Street3                0
Latitude               0
Census Tract (2010)    0
Census Block (2010)    0
dtype: int64

### Standardizing City Names

The `City` column contains some city names with inconsistent capitalization, such as `NEW YORK` and `New York`.

The city names are standardized to uppercase to maintain consistent formatting.

In [26]:
df["City"] = df["City"].str.upper()

In [27]:
df["City"].value_counts(dropna=False).head(20)

City
NEW YORK               19794
BROOKLYN               19225
BRONX                   9872
NaN                     5928
STATEN ISLAND           2064
FLUSHING                1983
JAMAICA                 1892
LONG ISLAND CITY        1148
ASTORIA                 1007
JACKSON HEIGHTS          862
WOODSIDE                 561
CORONA                   554
ELMHURST                 543
OZONE PARK               473
FOREST HILLS             468
RIDGEWOOD                406
SOUTH OZONE PARK         374
QUEENS VILLAGE           346
EAST ELMHURST            338
SOUTH RICHMOND HILL      329
Name: count, dtype: int64

In [63]:
id_columns = [
    "Record ID",
    "311 SR Number",
    "Business Unique ID",
    "Building Nbr",
    "Postcode",
    "Community Board",
    "Council District",
    "BIN",
    "BBL",
    "Census Block (2010)",
    "Census Tract (2010)"
]

df[id_columns].dtypes

Record ID               object
311 SR Number           object
Business Unique ID      object
Building Nbr            object
Postcode                object
Community Board        float64
Council District       float64
BIN                    float64
BBL                    float64
Census Block (2010)    float64
Census Tract (2010)    float64
dtype: object

In [65]:
df[
    ["Community Board", "Council District", "BIN", "BBL",
     "Census Block (2010)", "Census Tract (2010)"]
].head(10)

,Community Board,Council District,BIN,BBL,Census Block (2010),Census Tract (2010)
0,106.0,4.0,1020634.0,1.009358e+09,3000.0,70.0
1,407.0,20.0,4112199.0,4.049630e+09,2008.0,871.0
2,105.0,4.0,1087268.0,1.009950e+09,1005.0,119.0
3,107.0,6.0,1088786.0,1.011678e+09,5002.0,163.0
4,107.0,6.0,1088786.0,1.011678e+09,5002.0,163.0
5,303.0,41.0,3341712.0,3.014880e+09,1000.0,375.0
6,105.0,3.0,NaN,NaN,NaN,113.0
7,105.0,4.0,1034199.0,1.012580e+09,1007.0,96.0
8,402.0,26.0,4000456.0,4.000520e+09,1000.0,7.0
9,110.0,9.0,1089315.0,1.019520e+09,1000.0,257.0

## 9. Correcting Data Types

Some identifier and code-related columns are stored as numeric values.

These columns are identifiers rather than measurements, so they are converted to string format to preserve their values correctly.

In [28]:
id_numeric_columns = [
    "Community Board",
    "Council District",
    "BIN",
    "BBL",
    "Census Block (2010)",
    "Census Tract (2010)"
]

for column in id_numeric_columns:
    df[column] = df[column].astype("Int64").astype("string")

In [67]:
#Checking
df[id_numeric_columns].dtypes

Community Board        string[python]
Council District       string[python]
BIN                    string[python]
BBL                    string[python]
Census Block (2010)    string[python]
Census Tract (2010)    string[python]
dtype: object

In [69]:
df.dtypes

Record ID                            object
Intake Date                  datetime64[ns]
Intake Channel                       object
311 SR Number                        object
Business Category                    object
Complaint Code                       object
Business Unique ID                   object
Business Name                        object
Result Date                  datetime64[ns]
Result                               object
Referred To                          object
Contract Cancelled Amount             Int64
Refund Amount                         Int64
Address Type                         object
Building Nbr                         object
Street1                              object
City                                 object
State                                object
Postcode                             object
Borough                              object
Community Board              string[python]
Council District             string[python]
BIN                          string[python]
BBL                          string[python]
NTA                                  object
Census Block (2010)          string[python]
Census Tract (2010)          string[python]
Latitude                            float64
Longitude                           float64
dtype: object

In [70]:
id="placeholder_check"
for column in df.select_dtypes(include="object").columns:
    print("\n", column)
    print(df[column].value_counts().head(10))

 Record ID
Record ID
006935-2026-CMPL    4
024350-2023-CMPL    3
13216-2023-CMPL     2
077948-2025-CMPL    2
12415-2023-CMPL     2
12416-2023-CMPL     2
9692-2023-CMPL      2
13302-2023-CMPL     2
003279-2026-CMPL    2
12440-2023-CMPL     2
Name: count, dtype: int64

 Intake Channel
Intake Channel
311                 53771
Online              17524
Email/Fax            2634
Hardcopy             2073
Cloned                264
Phone                 245
Walk-In                11
External Affairs        5
Name: count, dtype: int64

 311 SR Number
311 SR Number
0               246
311-19304092      9
311-19314560      5
311-19344528      5
311-15568788      3
311-19327514      3
311-19314272      3
311-19333190      2
311-15089803      2
311-15213741      2
Name: count, dtype: int64

 Business Category
Business Category
Other                          11105
Misc Non-Food Retail            6077
Tow Truck Company               5587
Restaurant                      3835
Supermarket                     3460
Grocery-Retail                  3367
Home Improvement Contractor     3341
Garage & Parking Lot            3054
Secondhand Dealer - Auto        2422
Tobacco Retail Dealer           2305
Name: count, dtype: int64

 Complaint Code
Complaint Code
Advertising/Misleading - A02    6407
Overcharge                      6288
Unlicensed                      6251
Exchange/Refund/Return          5056
Non-Delivery of Goods - N01     4986
Sidewalk Blocked                3224
Other - Z01                     2945
Billing Dispute - B02           2876
Lost/Stolen/Damaged Property    2329
Damaged Goods - D01             1411
Name: count, dtype: int64

 Business Unique ID
Business Unique ID
BA-1103959-2022    128
BA-1669484-2023    103
BA-1120307-2022     82
BA-1688781-2024     79
BA-1770004-2026     67
BA-1690898-2024     62
BA-1666039-2023     61
BA-1670797-2023     59
BA-1671602-2023     50
BA-1754688-2025     46
Name: count, dtype: int64

 Business Name
Business Name
MEMORIAL SLOAN KETTERING CANCER CENTER            384
Unknown                                           249
NYC Soft Ice Cream Truck owned by Eddie Cumart    199
ROSARIO FAMILY BEST CIGARS LLC                    198
No name                                           145
unknown                                           138
CVS                                               135
ROSARIO FAMILY CIGAR BUISNESS                     133
no name                                           128
BEN & NINO AUTO REPAIR INC.                       125
Name: count, dtype: int64

 Result
Result
Referred                                 25633
Requested Information Not Provided       23658
Complaint Review Complete                11060
Insufficient Info Received                4885
No Jurisdiction                           1919
Information Provided                      1412
Advised to Sue - ATS                      1302
Duplicate Complaint - DUP                 1051
Resolved and Consumer Satisfied - SPF     1007
No Business Response - NVR                 996
Name: count, dtype: int64

 Referred To
Referred To
Other                                        7484
NYC Department of Sanitation                 3820
Not Specified                                2442
NYC Police Department                        1833
NYS Office of the Attorney General           1347
NYC Department of Health & Mental Hygiene    1244
NYC Department of Transportation             1036
Court System                                 1024
NYS Department of Agriculture and Markets     866
NYS Department of Motor Vehicles              798
Name: count, dtype: int64

 Address Type
Address Type
Complete Address               69639
Cross Street (Intersection)     2859
Place (Landmark)                 239
Block                            142
P.O. Box                           8
Name: count, dtype: int64

 Building Nbr
Building Nbr
1       421
633     348
323     320
200     302
504     286
2       281
25      280
2603    239
150     222
55      218
Name: count, dtype: int64

 Street1
Street1
BROADWAY         2437
3RD AVE          1203
5TH AVE           922
NORTHERN BLVD     815
QUEENS BLVD       587
8TH AVE           552
ATLANTIC AVE      494
2ND AVE           493
FLATBUSH AVE      483
BOSTON RD         479
Name: count, dtype: int64

 City
City
BROOKLYN            18322
NEW YORK            17890
BRONX                9504
STATEN ISLAND        1967
New York             1901
FLUSHING             1860
JAMAICA              1811
LONG ISLAND CITY     1033
ASTORIA               935
Brooklyn              903
Name: count, dtype: int64

 State
State
NY             70657
NJ               384
CA               297
Outside USA      135
FL               133
TX               115
PA               112
WA                70
CO                69
MN                68
Name: count, dtype: int64

 Postcode
Postcode
11201    1432
10036    1274
10019    1274
10001    1187
11235    1167
11101    1091
10017     980
11372     966
10467     952
11220     950
Name: count, dtype: int64

 Borough
Borough
Manhattan        19712
Brooklyn         19305
Queens           15394
Bronx             9954
Staten Island     1983
Outside NYC        566
Name: count, dtype: int64

 NTA
NTA
MN17    3198
MN13    1628
MN25    1431
MN24    1209
QN22    1076
QN31    1035
MN19    1027
BK38    1012
BK17    1006
MN23     923
Name: count, dtype: int64

In [71]:
df["Business Name"] = df["Business Name"].replace(
    ["Unknown", "unknown", "No name", "no name"],
    np.nan
)

df["City"] = df["City"].str.upper()

In [72]:
df["Business Name"].value_counts().head(10)

Business Name
MEMORIAL SLOAN KETTERING CANCER CENTER             384
NYC Soft Ice Cream Truck owned by Eddie Cumart     199
ROSARIO FAMILY BEST CIGARS LLC                     198
CVS                                                135
ROSARIO FAMILY CIGAR BUISNESS                      133
BEN & NINO AUTO REPAIR INC.                        125
NYC Soft Ice Cream Trucks owned by Eddie Cumart    119
Car Wash                                           111
Clutch Towing Inc                                  106
Target                                              98
Name: count, dtype: int64

In [73]:
df["City"].value_counts().head(15)

City
NEW YORK            19794
BROOKLYN            19225
BRONX                9872
STATEN ISLAND        2064
FLUSHING             1983
JAMAICA              1892
LONG ISLAND CITY     1148
ASTORIA              1007
JACKSON HEIGHTS       862
WOODSIDE              561
CORONA                554
ELMHURST              543
OZONE PARK            473
FOREST HILLS          468
RIDGEWOOD             406
Name: count, dtype: int64

In [74]:
for column in df.select_dtypes(include="object").columns:
    values = df[column].dropna().astype(str)
    suspicious = values[values.isin(["-", "N/A", "NA", "Unknown", "unknown", "None", "none", "0"])]
    
    if len(suspicious) > 0:
        print(column)
        print(suspicious.value_counts())

311 SR Number
311 SR Number
0    246
Name: count, dtype: int64
Business Name
Business Name
none    38
0        1
Name: count, dtype: int64
Building Nbr
Building Nbr
0    1
Name: count, dtype: int64
Street1
Street1
0    1
Name: count, dtype: int64
Postcode
Postcode
0    1
Name: count, dtype: int64

In [77]:
df["311 SR Number"] = df["311 SR Number"].replace("0", np.nan)

df["Business Name"] = df["Business Name"].replace(
    ["none", "0"],
    np.nan
)

df["Building Nbr"] = df["Building Nbr"].replace("0", np.nan)

df["Street1"] = df["Street1"].replace("0", np.nan)

df["Postcode"] = df["Postcode"].replace("0", np.nan)

In [76]:
for column in ["311 SR Number", "Business Name", "Building Nbr", "Street1", "Postcode"]:
    print(column, (df[column] == "0").sum())

311 SR Number 0
Business Name 0
Building Nbr 0
Street1 0
Postcode 0

In [78]:
print("Intake Date:")
print(df["Intake Date"].min())
print(df["Intake Date"].max())

print("\nResult Date:")
print(df["Result Date"].min())
print(df["Result Date"].max())

Intake Date:
2022-09-22 00:00:00
2026-07-27 00:00:00

Result Date:
2023-07-02 00:00:00
2026-07-27 00:00:00

In [79]:
invalid_dates = df[df["Result Date"] < df["Intake Date"]]

print("Invalid date rows:", len(invalid_dates))

Invalid date rows: 2

In [80]:
invalid_dates = df[df["Result Date"] < df["Intake Date"]]

invalid_dates[
    ["Record ID", "Intake Date", "Result Date", "Result"]
]

              Record ID Intake Date Result Date                Result
28866  042731-2024-CMPL  2024-07-27  2024-07-26              Referred
63892   10355-2023-CMPL  2023-07-27  2023-07-20  Advised to Sue - ATS

In [81]:
df.loc[df["Result Date"] < df["Intake Date"], "Result Date"] = pd.NaT

In [82]:
missing_final = df.isnull().sum().sort_values(ascending=False)

missing_final[missing_final > 0]

Contract Cancelled Amount    76481
Refund Amount                75018
Referred To                  48525
311 SR Number                23010
BBL                          15379
BIN                          15379
Census Block (2010)          13454
NTA                          13454
Building Nbr                 12487
Complaint Code               10777
Census Tract (2010)          10595
Community Board              10592
Council District             10592
Latitude                     10127
Longitude                    10127
Borough                       9613
City                          5928
Business Name                 4080
Postcode                      3748
State                         3721
Street1                       3691
Address Type                  3640
Business Unique ID            2497
Business Category             1398
Result Date                      2
dtype: int64

## 10. Checking Duplicate Records

Duplicate records can affect the accuracy of analysis, so the dataset is checked for exact duplicate rows.

Records with the same `Record ID` are also examined separately because the same identifier may appear in multiple rows with different information.

In [83]:
duplicate_count = df.duplicated().sum()

print("Duplicate rows:", duplicate_count)

Duplicate rows: 0

In [84]:
print("Duplicate Record IDs:", df["Record ID"].duplicated().sum())

Duplicate Record IDs: 137

In [85]:
duplicate_ids = df[df["Record ID"].duplicated(keep=False)]

print("Rows with duplicate Record IDs:", len(duplicate_ids))

Rows with duplicate Record IDs: 271

No exact duplicate rows were found in the dataset.

Some `Record ID` values occur more than once, but these records contain different information in other columns. Therefore, they were retained rather than removed.

In [86]:
duplicate_ids[
    ["Record ID", "Intake Date", "Business Name", "Complaint Code", "Result"]
].sort_values("Record ID").head(30)

,Record ID,Intake Date,Business Name,Complaint Code,Result
1109,001275-2026-CMPL,2026-01-18,Paypal Inc,Exchange/Refund/Return,Referred to Outside - RTO
1110,001275-2026-CMPL,2026-01-18,"PayPal, Inc.",Exchange/Refund/Return,Referred to Outside - RTO
2664,003279-2026-CMPL,2026-02-14,Shop Fair,Overcharge,Requested Information Not Provided
69713,003279-2026-CMPL,2026-02-14,A & J MEAT MARKET INC,Overcharge; Cashless Business,Complaint Review Complete
71983,004608-2026-CMPL,2026-03-04,The Clutterless Company,Overcharge,Complaint Review Complete
66895,004608-2026-CMPL,2026-03-04,The Clutterless Company,NaN,Requested Information Not Provided
76027,006266-2026-CMPL,2026-03-24,LifeX Research Corporation,Misrepresentation - M01,Referred
70395,006266-2026-CMPL,2026-03-24,LifeX Research Corporation,Misrepresentation - M01,Complaint Review Complete
75826,006935-2026-CMPL,2026-04-01,26 MOTORS COMMERCIAL LLC,Contract or Billing Dispute,Referred
69974,006935-2026-CMPL,2026-04-01,26 MOTORS,Contract or Billing Dispute,Requested Information Not Provided
69580,006935-2026-CMPL,2026-04-01,26 MOTORS COMMERCIAL LLC,Contract or Billing Dispute,Requested Information Not Provided
76486,006935-2026-CMPL,2026-04-01,26 MOTORS,Contract or Billing Dispute,Referred
76301,008695-2026-CMPL,2026-04-21,LA VICTORIA FOUNDATION,Non-Delivery of Goods - N01,Requested Information Not Provided
67261,008695-2026-CMPL,2026-04-21,LA VICTORIA FOUNDATION,Non-Delivery of Goods - N01,Complaint Review Complete
71577,008711-2026-CMPL,2026-04-21,7F’S CAFE INC.,Unlicensed,Inspection Requested
73631,008711-2026-CMPL,2026-04-21,7F’S CAFE INC.,Unlicensed,Inspection Requested
4807,014685-2023-CMPL,2023-08-15,東粵海鮮酒家 Dong Yue seafood restaurant,NaN,Requested Information Not Provided
4806,014685-2023-CMPL,2023-08-15,Dong Yue Seafood Restaurant,NaN,Requested Information Not Provided
5339,015348-2023-CMPL,2023-08-08,GAMESTOP INC.,Exchange/Refund/Return,Resolved and Consumer Satisfied - SPF
5338,015348-2023-CMPL,2023-08-08,Gamestop Corp.,Exchange/Refund/Return,Resolved and Consumer Satisfied - SPF
5587,015635-2023-CMPL,2023-08-12,Chimichurri Charcoal Kitchen Corp.,NaN,Referred
5586,015635-2023-CMPL,2023-08-12,Chimichurri Charcoal Chicken,NaN,Referred
9656,020369-2023-CMPL,2023-10-12,"SCALISE, FIORE",NaN,Referred to Hearing - RTH
9655,020369-2023-CMPL,2023-10-12,fiore general contracting,NaN,Referred to Hearing - RTH
10826,021690-2023-CMPL,2023-10-27,NaN,NaN,Complaint Review Complete
10827,021690-2023-CMPL,2023-10-27,renewal by anderson of long island,NaN,Complaint Review Complete
11706,022690-2023-CMPL,2023-11-10,VICTORY MITSUBISHI,Contract Terms Misleading or Not Disclosed,Advised to Sue - ATS
11705,022690-2023-CMPL,2023-11-10,SPARTAN AUTO GROUP LLC,Contract Terms Misleading or Not Disclosed,Advised to Sue - ATS
13223,024350-2023-CMPL,2025-02-18,New Leaf Home Improvement LLC,NaN,Duplicate Complaint - DUP
13222,024350-2023-CMPL,2025-02-18,H G RENOVATION CORP.,NaN,Duplicate Complaint - DUP

In [87]:
duplicate_ids.groupby("Record ID").size().value_counts()

2    132
4      1
3      1
Name: count, dtype: int64

In [88]:
print("Total rows:", len(df))
print("Unique Record IDs:", df["Record ID"].nunique())

Total rows: 76527
Unique Record IDs: 76390

In [89]:
print("Final shape:", df.shape)
print("Exact duplicate rows:", df.duplicated().sum())

Final shape: (76527, 29)
Exact duplicate rows: 0

In [101]:
missing = df.isnull().sum()
missing = missing[missing > 0].sort_values(ascending=False)

print(missing)

Contract Cancelled Amount    76481
Refund Amount                75018
Referred To                  48525
311 SR Number                23010
BBL                          15379
BIN                          15379
Census Block (2010)          13454
NTA                          13454
Building Nbr                 12487
Complaint Code               10777
Census Tract (2010)          10595
Community Board              10592
Council District             10592
Latitude                     10127
Longitude                    10127
Borough                       9613
City                          5928
Business Name                 4080
Postcode                      3748
State                         3721
Street1                       3691
Address Type                  3640
Business Unique ID            2497
Business Category             1398
Result Date                      2
dtype: int64

In [104]:
df.to_csv("../data/cleaned/DCWP_Consumer_Complaints_Cleaned.csv", index=False)

print("Cleaned dataset saved successfully!")
print("Rows:", len(df))
print("Columns:", len(df.columns))

Cleaned dataset saved successfully!
Rows: 76527
Columns: 29

# Data Cleaning Summary

## Dataset Overview

- Original dataset size: 76,527 rows and 33 columns
- Final cleaned dataset size: 76,527 rows and 29 columns
- Exact duplicate rows found: 0

## Cleaning Steps Performed

### 1. Removed Highly Sparse Columns
The following columns were removed because they contained an extremely high percentage of missing values and provided limited analytical value:

- Street2
- Street3
- Unit Type
- Apt/Suite

### 2. Cleaned Financial Columns
`Contract Cancelled Amount` and `Refund Amount` were cleaned by removing currency symbols and commas and converting them to numeric data types.

Missing financial values were retained rather than automatically replacing them with zero.

### 3. Cleaned Date Columns
`Intake Date` and `Result Date` were converted to datetime format.

Two records contained a Result Date earlier than the Intake Date. Since the correct date could not be determined from the dataset, these inconsistent Result Date values were set to missing.

### 4. Cleaned Categorical Data
- City names were standardized to uppercase.
- Obvious placeholder values such as `Unknown`, `No name`, `none`, `0`, and `-` were treated as missing where appropriate.
- `-` in `Referred To` was replaced with `Not Specified`.

### 5. Data Type Correction
Identifier and code-related columns such as Community Board, Council District, BIN, BBL, Census Block, and Census Tract were converted from numeric representation to string format to preserve their identifier nature.

### 6. Duplicate Handling
No exact duplicate rows were found.

Some `Record ID` values occurred multiple times. These records were retained because the corresponding rows contained differences in fields such as Business Name, Complaint Code, or Result and therefore were not exact duplicates.

## Final Validation

- Final rows: 76,527
- Final columns: 29
- Exact duplicate rows: 0
- Date fields converted successfully
- Financial fields converted to numeric format
- Identifier fields preserved as strings
- Remaining missing values were retained where appropriate

The cleaned dataset was saved as:

`DCWP_Consumer_Complaints_Cleaned.csv`

In [97]:
print("Final dataset shape:", df.shape)
print("Exact duplicate rows:", df.duplicated().sum())
print("Cleaning completed successfully.")

Final dataset shape: (76527, 29)
Exact duplicate rows: 0
Cleaning completed successfully.

In [105]:
df.to_csv("../data/cleaned/DCWP_Consumer_Complaints_Cleaned.csv", index=False)

print("Cleaned dataset saved successfully!")

Cleaned dataset saved successfully!